### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [galczo5/open-midi-controller#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by galczo5** [comment]
Hi, Thx! 
Decided to go with MIT license. 
Added in https://github.com/galczo5/open-midi-controller/commit/51c49bdbb674453256d2eeee2dc2bf11105c9ed2
